In [ ]:
#Pandas serve para Manipular dados
import pandas as pd
#Vizualização básica de dados
import matplotlib as mt
#Seaborn serve para Mostrar gráficos melhores
import seaborn as sb
#Numpy serve para Operações aritimedicas
import numpy as np

In [2]:
df = pd.read_csv("D:/Analise_Vendas_Supermercado/Data_Super.csv")
display(df)

,id_produto,nome_produto,marca,categoria,gramatura,preco,estoque_unidades,fornecedor,validade
0,1,Vinagre de Álcool 750ml,Toscano,Mercearia,750ml,16.78,33,Atacado União,2027-08-04
1,2,Leite em Pó 400g,Ninho,Laticínios,400g,20.96,46,Compra Direta,2026-02-18
2,3,Filé de Tilápia 400g,netuno,Açougue,400g,25.44,328,Alimentos Brasil,2026-04-25
3,4,Iogurte Natural 170g,Nestlé,Laticínios,170g,22.12,398,Hortifruti São José,2026-01-01
4,5,Leite Desnatado 1L,Italac,Laticínios,1L,6.25,243,Hortifruti São José,2026-06-19
...,...,...,...,...,...,...,...,...,...
9995,9996,"Água Mineral 1,5L",NaN,Bebidas,"1,5L",19.11,219,Atacado União,2027-10-17
9996,9997,Vinagre de Álcool 750ml,Toscano,Mercearia,750ml,6.64,280,Hortifruti São José,2026-11-04
9997,9998,Esponja de Limpeza 3 un,Ypê,Limpeza,3 un,5.55,286,Higiene & Cia,2027-03-28
9998,9999,Esponja de Limpeza 3 un,Ypê,Limpeza,3 un,14.22,165,Atacado União,2027-10-11
9999,10000,Açúcar Refinado 1kg,Caravelas,Mercearia,1kg,6.95,433,Higiene & Cia,2026-06-29

In [ ]:
#Ver o número de linhas e colunas
print("--=+=--"*4)
print(f"{df.shape[0]} Linhas\n{df.shape[1] } Colunas")
print("--=+=--"*4)
display('Nome das Colunas:', df.columns.tolist())
print("--=+=--"*4)
#Usar o .tolist para melhorar o print dos nomes das colunas

--=+=----=+=----=+=----=+=--
10000 Linhas
9 Colunas
--=+=----=+=----=+=----=+=--

'Nome das Colunas:'

['id_produto',
 'nome_produto',
 'marca',
 'categoria',
 'gramatura',
 'preco',
 'estoque_unidades',
 'fornecedor',
 'validade']

--=+=----=+=----=+=----=+=--

In [28]:
valores_nulos = df.isnull().sum()
print(valores_nulos)
print("---"*10)
print("Total de Linhas em Branco:",valores_nulos.sum())

id_produto            0
nome_produto        267
marca               275
categoria           185
gramatura           218
preco               247
estoque_unidades    187
fornecedor          249
validade            220
dtype: int64
------------------------------
Total de Linhas em Branco: 1848

In [29]:
df = df.dropna()
display(df)

,id_produto,nome_produto,marca,categoria,gramatura,preco,estoque_unidades,fornecedor,validade
0,1,Vinagre de Álcool 750ml,Toscano,Mercearia,750ml,16.78,33,Atacado União,2027-08-04
1,2,Leite em Pó 400g,Ninho,Laticínios,400g,20.96,46,Compra Direta,2026-02-18
2,3,Filé de Tilápia 400g,netuno,Açougue,400g,25.44,328,Alimentos Brasil,2026-04-25
3,4,Iogurte Natural 170g,Nestlé,Laticínios,170g,22.12,398,Hortifruti São José,2026-01-01
4,5,Leite Desnatado 1L,Italac,Laticínios,1L,6.25,243,Hortifruti São José,2026-06-19
...,...,...,...,...,...,...,...,...,...
9994,9995,Açúcar Refinado 1kg,Caravelas,Mercearia,1kg,"R$ 22,37",412,Atacado União,2026-10-21
9996,9997,Vinagre de Álcool 750ml,Toscano,Mercearia,750ml,6.64,280,Hortifruti São José,2026-11-04
9997,9998,Esponja de Limpeza 3 un,Ypê,Limpeza,3 un,5.55,286,Higiene & Cia,2027-03-28
9998,9999,Esponja de Limpeza 3 un,Ypê,Limpeza,3 un,14.22,165,Atacado União,2027-10-11
9999,10000,Açúcar Refinado 1kg,Caravelas,Mercearia,1kg,6.95,433,Higiene & Cia,2026-06-29

In [63]:
display(df[["preco","id_produto"]].head(306))
display(df.info())
#Formatos errados, todos com excessão do ID_Produto estão em STR

     preco  id_produto
0    16.78           1
1    20.96           2
2    25.44           3
3    22.12           4
4     6.25           5
..     ...         ...
356  13.43         357
358  56.99         359
359   9.15         360
361  17.99         362
362  31.23         363

[306 rows x 2 columns]

<class 'pandas.DataFrame'>
Index: 8289 entries, 0 to 9999
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id_produto        8289 non-null   int64
 1   nome_produto      8289 non-null   str
 2   marca             8289 non-null   str
 3   categoria         8289 non-null   str
 4   gramatura         8289 non-null   str
 5   preco             8289 non-null   str
 6   estoque_unidades  8289 non-null   str
 7   fornecedor        8289 non-null   str
 8   validade          8289 non-null   datetime64[us]
dtypes: datetime64[us](1), int64(1), str(7)
memory usage: 1.2 MB

None

In [71]:
#Padronização e formatando os tipos de dados corretamente
df["validade"] = pd.to_datetime(df["validade"], format="mixed")
df["validade"] = pd.to_datetime(df["validade"], format="%Y-%m-%d")
df["preco"] = pd.to_numeric(df["preco"].astype("string").str.replace("R$","",regex=False).str.replace(" ","",regex=False).str.replace(",", ".",regex=False).str.replace("preçopendente", "",regex=False))
df["estoque_unidades"] = pd.to_numeric(df["estoque_unidades"].astype("string").str.replace(" ", "",regex=False).str.replace("un","",regex=False))



print(df.info())
display(df.head(100))

<class 'pandas.DataFrame'>
Index: 8289 entries, 0 to 9999
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id_produto        8289 non-null   int64
 1   nome_produto      8289 non-null   str
 2   marca             8289 non-null   str
 3   categoria         8289 non-null   str
 4   gramatura         8289 non-null   str
 5   preco             8231 non-null   Float64
 6   estoque_unidades  8289 non-null   Int64
 7   fornecedor        8289 non-null   str
 8   validade          8289 non-null   datetime64[us]
dtypes: Float64(1), Int64(1), datetime64[us](1), int64(1), str(5)
memory usage: 1.1 MB
None

,id_produto,nome_produto,marca,categoria,gramatura,preco,estoque_unidades,fornecedor,validade
0,1,Vinagre de Álcool 750ml,Toscano,Mercearia,750ml,16.78,33,Atacado União,2027-08-04
1,2,Leite em Pó 400g,Ninho,Laticínios,400g,20.96,46,Compra Direta,2026-02-18
2,3,Filé de Tilápia 400g,netuno,Açougue,400g,25.44,328,Alimentos Brasil,2026-04-25
3,4,Iogurte Natural 170g,Nestlé,Laticínios,170g,22.12,398,Hortifruti São José,2026-01-01
4,5,Leite Desnatado 1L,Italac,Laticínios,1L,6.25,243,Hortifruti São José,2026-06-19
...,...,...,...,...,...,...,...,...,...
105,106,Absorvente 8 unidades,Always,Higiene e Beleza,8 unidades,36.15,39,Hortifruti São José,2026-04-25
106,107,Desodorante Aerosol 150ml,Nivea,Higiene e Beleza,150ml,22.77,288,Distribuidora Central,2027-07-27
107,108,Lentilha 500g,Camil,Arroz e Grãos,500g,12.37,92,Compra Direta,2026-05-19
108,109,Manteiga 200g,aviação,Laticínios,200g,39.62,201,Hortifruti São José,2026-05-11
109,110,Massa para Pizza 300g,mezzani,Massas,300g,2.53,338,Higiene & Cia,2027-09-22